apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-app
      mountPath: /usr/share/nginx/html    
    ports:
      - containerPort: 80
        name: "http-server"
  volumes:
  - name: nginx-app
    persistentVolumeClaim:
      claimName: app-data-pvc       
 
